[package]
authors = ["meh. <meh@schizofreni.co>"]
description = "Linux uinput definitions."
keywords = [
    "linux",
    "input",
]
license = "WTFPL"
name = "uinput-sys"
repository = "https://github.com/meh/rust-uinput-sys"
version = "0.1.5"

[dependencies]
libc = "0.2"
nix = "0.9.0"
